In [30]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/aps0611/tchr_capstone_case/main/df1.csv')

In [32]:
df.head(5)

,Unnamed: 0,timestamp,candidate_name,educational_qualification,level,degree,fresher_experienced,work_ex,current_CTC,expected_CTC,notice_period,current_city,skills,english_level,job_reference,candidate_status,skill_count,status
0,0,2022-07-04 19:16:04,ANIKET DHANRAJ JADHAO,m.sc. geoinformatics,M,geoinformatics,fresher,NaN,0,3,0.0,akola,1.arcgis\n2.q-gis\n3.google earth pro.,4,LinkedIn,Shortlisted for 2nd Round,1,Shortlisted
1,1,2022-07-04 19:16:04,Darshan Pravin Patel,pursuing graduation/ post graduation in geolog...,B,geoinformatics,fresher,NaN,0,6,0.0,akola,"arcgis, qgis, google earthpro",4,LinkedIn,Shortlisted for 2nd Round,2,Shortlisted
2,2,2022-07-04 19:24:16,ANURAJ MAHADEV THROAT,a diploma holder with a geoinformatics background,D,geoinformatics,fresher,1.0,0,3,0.0,kolhapur,1.communication 2.leadership 3.creativity,3,Friend,Can Consider 3/5,0,Revisit
3,3,2022-07-04 19:25:31,Suraj Ramchandra Patil,"m.a/m.sc. geography with gis background, a dip...",M,geoinformatics,fresher,0.0,0,3,0.0,kolhapur maharashtr,"qgis,arcgis,erdas,autocad,elvis",2,LinkedIn,Reject,3,Reject
4,4,2022-07-04 19:48:28,Komal Prakash Pawar,m.a/m.sc. geography with gis background,M,geography,experienced,3.0,2,3,0.5,bangalore,"qgis,arcgis, global, mapper",1,Social Media,Shortlisted for 2nd Round,2,Shortlisted

In [33]:
addresses = df.current_city.value_counts().index

In [34]:
import pandas as pd
from geopy.geocoders import Nominatim

class FarmGeocoder:
    def __init__(self):
        self.geocoder = Nominatim(user_agent="FarmGeocoder")

    def geocode_address(self, address):
        print(address)
        location = self.geocoder.geocode(address)
        if location is not None:
            latitude = location.latitude
            longitude = location.longitude
            return latitude, longitude
        else:
            return None

if __name__ == "__main__":
    # Your addresses list
    addresses = addresses

    # Create a DataFrame
    df = pd.DataFrame({"Address": addresses})

    # Create a new instance of FarmGeocoder
    geocoder = FarmGeocoder()

    # Geocode addresses and create new columns for latitude and longitude
    df[['Latitude', 'Longitude']] = df['Address'].apply(lambda x: pd.Series(geocoder.geocode_address(x) if geocoder.geocode_address(x) else [None, None]))

    # Save the DataFrame to a new Excel file
    df.to_excel("geocoded_addresses.xlsx", index=False)

pune
pune
hyderabad
hyderabad
hyderabad
hyderabad
kolhapur
kolhapur
bangalore
bangalore
bangalore
bangalore
mumbai
mumbai
akola
akola
kolkata
kolkata
delhi

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=delhi&format=json&limit=1

delhi
pune
pune
solapur
solapur
bhubaneswar
bhubaneswar
aligarh
aligarh
mumbai
mumbai

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=mumbai+&format=json&limit=1

chennai
chennai
dhule
dhule
visakhapatnam
visakhapatnam
jalgaon
jalgaon
visakhapatnam
visakhapatnam
sangola
sangola
surat

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=surat&format=json&limit=1

surat
bengaluru
bengaluru
bengaluru
bengaluru
bhubaneswar
bhubaneswar
meerut
meerut
thrissur
thrissur
thane
thane
nagpur
nagpur
aurangabad
aurangabad
salem
salem
nashik
nashik
bhuj
bhuj
banglore
banglore
asansol
asansol
chennai
chennai
kolkata
kolkata
solapur
solapur
trivandrum
trivandrum
nayagarh
nayagarh
amaravati
amaravati
kasaragod
kasaragod
bhadrak,odisha
bhadrak,odisha
kochi

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=kochi&format=json&limit=1

kochi
kalaburagi
kalaburagi
bahadurgarh
bahadurgarh
ramanathapuram
ramanathapuram
palanpur
palanpur
hydrabad
hydrabad
chhindwara
chhindwara
latur
latur
ghaziabad
ghaziabad
jajpur
jajpur
varanasi
varanasi
noida
noida
navi mumbai
navi mumbai
kakinada
kakinada
ranchi
ranchi
sangli
sangli
jaipur
jaipur
malappuram
malappuram
kalyan
kalyan
kozhikode
kozhikode
hyderbad
hyderbad
bhimavaram
bhimavaram
ujjain
ujjain
bhalki
bhalki
hydrabad
hydrabad
ernakulam
ernakulam
haryana
haryana
jharsuguda
jharsuguda
islampur
islampur
kanpur nagar
kanpur nagar
airoli, navi mumbai
airoli, navi mumbai
burdwan, west bengal
burdwan, west bengal
mysore
mysore
rewa (m.p.)
indore
indore
nainital
nainital
rajahmundry
rajahmundry
unnao
unnao
davangere
davangere
jaysingpur
jaysingpur
vijayawada
vijayawada
pendraroad
palani
palani

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=palani&format=json&limit=1

dehradun
dehradun
karimnagar
karimnagar
jaipur, rajasthan
jaipur, rajasthan
puri, odisha.
puri, odisha.
ballia, uttar pradesh
ballia, uttar pradesh
bhalki-585328
bhalki-585328
bilaspur
bilaspur
krishnagiri
krishnagiri
howrah
howrah
kolkata, west bengal
kolkata, west bengal
vizag
vizag
eluru
eluru
west godavari
west godavari
bikaner
bikaner
vishakhapatnam
gurugram
gurugram
alappuzha
alappuzha
mumbai suburban
mumbai suburban
sangamner
sangamner
madurai
madurai
sikar
sikar
tirunelveli
tirunelveli
midnapore
midnapore
midnapore
midnapore
medinipur
medinipur
ambattur, chennai
ambattur, chennai
bangalore.
bangalore.
bengalore
bengalore
zawar
zawar
ysr kadapa
ysr kadapa
kendrapara , odisha
kendrapara , odisha
kendrapara, odisha
kendrapara, odisha
vijayawada
vijayawada
asansol
asansol
navi mumbai
navi mumbai
kendrapara- odisha
kendrapara- odisha
new panvel
new panvel
new delhi
new delhi
noida
noida
amravati
amravati
pusad yavatmal
pusad yavatmal
satara
satara
jodhpur
jodhpur
anantapur, andhra pradesh state
andheri east mumbai maharashtra
andheri east mumbai maharashtra
trivandrum
trivandrum
nanded
nanded
kallakurichi
kallakurichi
angul, odisha
angul, odisha
imphal
imphal
baidyabati
baidyabati
ballarpur
ballarpur
nagpur
nagpur
malkapur
malkapur
bankura
bankura
trivandrum, kerala, india
trivandrum, kerala, india
nipani
nipani
patna,bihar
patna,bihar
kagal kolhapur
kagal kolhapur
anjuna
anjuna
panjim goa
panjim goa
himayatnagar
himayatnagar
patna, bihar
patna, bihar
kachchh (bhuj)
kachchh (bhuj)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=kachchh+%28bhuj%29&format=json&limit=1

mahabubabad, telangana
mahabubabad, telangana
gandhinagar
gandhinagar
veraval
veraval
kolhapur maharashtr
panjim, goa
panjim, goa
aligarh
aligarh
vadodara
vadodara
nandura
nandura
gundlupet
gundlupet
karad, dist satara maharashtra
dombivali
dombivali
maldah
maldah
mandvi
mandvi
vadodara, gujarat
vadodara, gujarat
namakkal
namakkal
tiruvannamalai
tiruvannamalai
ramanathapuram
ramanathapuram
patna
patna
periyapatna
periyapatna
khandala
khandala
nanded
nanded
ghoradongri
ghoradongri
bengaluru, karnataka
bengaluru, karnataka
kanyakumari
kanyakumari
sambhajinagar maharashtra
sambhajinagar maharashtra
east medinipur
east medinipur
cuddalore
cuddalore
chalisgaon
chalisgaon
cuttack
cuttack
coimbatore

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=coimbatore+&format=json&limit=1

coimbatore
new delhi
new delhi
naya raipur, chhattisgarh.
naya raipur, chhattisgarh.
shillong
shillong
pune vishrantwadi
pune vishrantwadi
krishnagiri
krishnagiri
baroda
baroda
uran, navi mumbai
uran, navi mumbai
trichy
trichy
ahmedabad
ahmedabad
adimaly,kerala
adimaly,kerala
bengaluru.
bengaluru.
hyderabad india
hyderabad india
villupuram
villupuram
salem
salem
kohima, nagaland
kohima, nagaland
karad
karad
ahmedabad
ahmedabad
thoothukudi
thoothukudi
faridabad
faridabad
joda
joda
tirunelveli
tirunelveli
karad, satara dist. maharashtra
shegaon
shegaon
kannur
kannur
guwahati
guwahati
bhuj - gujarat
bhuj - gujarat
bokaro steel city
bokaro steel city
karjat
karjat
bokaro steel city
bokaro steel city
mohali
mohali

In [35]:
df

                Address   Latitude  Longitude
0                  pune  18.521428  73.854454
1             hyderabad  17.360589  78.474061
2            hyderabad   17.360589  78.474061
3              kolhapur  16.702841  74.240533
4            bangalore   12.976794  77.590082
..                  ...        ...        ...
205      bhuj - gujarat  23.247245  69.668339
206  bokaro steel city   23.657960  86.083916
207              karjat  18.961778  73.377504
208   bokaro steel city  23.657960  86.083916
209              mohali  30.704117  76.717688

[210 rows x 3 columns]

In [50]:
new_col = {'Address':'current_city',
              'Latitude':'lat',
              'Longitude':'long'}

In [51]:
df.rename(columns=new_col, inplace=True)

In [52]:
df.to_csv('latlong.csv')

In [53]:
df1 = pd.read_csv('https://raw.githubusercontent.com/aps0611/tchr_capstone_case/main/df1.csv')

In [54]:
df1

,Unnamed: 0,timestamp,candidate_name,educational_qualification,level,degree,fresher_experienced,work_ex,current_CTC,expected_CTC,notice_period,current_city,skills,english_level,job_reference,candidate_status,skill_count,status
0,0,2022-07-04 19:16:04,ANIKET DHANRAJ JADHAO,m.sc. geoinformatics,M,geoinformatics,fresher,NaN,0,3,0.0,akola,1.arcgis\n2.q-gis\n3.google earth pro.,4,LinkedIn,Shortlisted for 2nd Round,1,Shortlisted
1,1,2022-07-04 19:16:04,Darshan Pravin Patel,pursuing graduation/ post graduation in geolog...,B,geoinformatics,fresher,NaN,0,6,0.0,akola,"arcgis, qgis, google earthpro",4,LinkedIn,Shortlisted for 2nd Round,2,Shortlisted
2,2,2022-07-04 19:24:16,ANURAJ MAHADEV THROAT,a diploma holder with a geoinformatics background,D,geoinformatics,fresher,1.0,0,3,0.0,kolhapur,1.communication 2.leadership 3.creativity,3,Friend,Can Consider 3/5,0,Revisit
3,3,2022-07-04 19:25:31,Suraj Ramchandra Patil,"m.a/m.sc. geography with gis background, a dip...",M,geoinformatics,fresher,0.0,0,3,0.0,kolhapur maharashtr,"qgis,arcgis,erdas,autocad,elvis",2,LinkedIn,Reject,3,Reject
4,4,2022-07-04 19:48:28,Komal Prakash Pawar,m.a/m.sc. geography with gis background,M,geography,experienced,3.0,2,3,0.5,bangalore,"qgis,arcgis, global, mapper",1,Social Media,Shortlisted for 2nd Round,2,Shortlisted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,440,2023-02-23 16:15:41,Bavithra Paramasivam,bachelor of engineerng in geoinformatics,B,geoinformatics,experienced,24.0,3.5,4.5,1.0,bangalore,qgis\nvector data handling\nattributes handlin...,4,Social Media,NaN,2,Not specified
441,441,2023-05-17 08:03:29,Shreyas RC,m.sc. geoinformatics,M,geoinformatics,experienced,NaN,0,6.5,0.0,bengaluru,1).deep learning and machine learning using py...,5,LinkedIn,NaN,0,Not specified
442,442,2023-05-17 09:53:20,Rohit Dharmaraj Mallah,b. sc. physics,B,other,experienced,12.0,2.3,3,1.0,thane,excel\npower bi\nqgis\njava atlas,4,LinkedIn,NaN,1,Not specified
443,443,2023-05-28 20:10:37,Sreekanth PA,pursuing graduation/ post graduation in geolog...,B,geoinformatics,fresher,NaN,0,4.5,0.0,tirunelveli,1. arcgis 2. qgis 3. python,4,LinkedIn,NaN,2,Not specified
444,444,2023-08-15 23:51:05,SANTOSH,mca,M,other,experienced,60.0,6,9,1.0,mohali,"arc software, qgis",4,LinkedIn,NaN,1,Not specified

In [56]:
df_new = pd.merge(df1,df, on='current_city', how='outer')

In [57]:
df_new.to_csv('df2.csv')
df_new.to_excel('df2.xlsx')

In [58]:
df_new['lat_long'] = df_new['lat'].astype(str) + ', ' + df_new['long'].astype(str)
df_new

,Unnamed: 0,timestamp,candidate_name,educational_qualification,level,degree,fresher_experienced,work_ex,current_CTC,expected_CTC,...,current_city,skills,english_level,job_reference,candidate_status,skill_count,status,lat,long,lat_long
0,0,2022-07-04 19:16:04,ANIKET DHANRAJ JADHAO,m.sc. geoinformatics,M,geoinformatics,fresher,NaN,0,3,...,akola,1.arcgis\n2.q-gis\n3.google earth pro.,4,LinkedIn,Shortlisted for 2nd Round,1,Shortlisted,20.761812,77.192116,"20.76181225, 77.1921156663574"
1,1,2022-07-04 19:16:04,Darshan Pravin Patel,pursuing graduation/ post graduation in geolog...,B,geoinformatics,fresher,NaN,0,6,...,akola,"arcgis, qgis, google earthpro",4,LinkedIn,Shortlisted for 2nd Round,2,Shortlisted,20.761812,77.192116,"20.76181225, 77.1921156663574"
2,64,2022-07-07 20:44:26,Pranali Chandrabhan Bhoyar,"b.sc. geology, pursuing graduation/ post gradu...",B,geoinformatics,fresher,NaN,0,5.5,...,akola,1. great communication skill\n2. leadership\n3...,3,LinkedIn,Poor English Communication,0,Poor English,20.761812,77.192116,"20.76181225, 77.1921156663574"
3,65,2022-07-07 20:44:57,Akshay eknath thakare,m.sc. geoinformatics,M,geoinformatics,fresher,NaN,0,3,...,akola,i have operate the arc gis software and google...,3,Social Media,Poor English Communication,0,Poor English,20.761812,77.192116,"20.76181225, 77.1921156663574"
4,67,2022-07-07 21:04:15,Sagar Dipak Mahalle,"b.sc. geology, m.sc. geoinformatics, pursuing ...",B,geoinformatics,fresher,NaN,0,3.6,...,akola,"1)gis software used: arcgis, qgis, google eart...",4,Other Reference / College /Alumni Group /,Poor English Communication,2,Poor English,20.761812,77.192116,"20.76181225, 77.1921156663574"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,433,2022-09-04 17:56:35,Dhruv Vishwakarma,b. tech. petroleum engineering,B,other,experienced,36.0,5.5,7,...,bahadurgarh,arcgis enterprise\narcgis server\ntechnical su...,4,Naukri.com,NaN,2,Not specified,28.660965,76.834676,"28.660964800000002, 76.83467647083376"
441,434,2022-09-07 23:38:53,Dhruv Vishwakarma,b.tech. petroleum engineering,B,other,experienced,36.0,4.68,6.5,...,bahadurgarh,arcgis enterprise\narcgis desktop\narcgis serv...,4,NaN,NaN,3,Not specified,28.660965,76.834676,"28.660964800000002, 76.83467647083376"
442,439,2022-11-27 22:15:40,sanjesh kumar,m.sc. geology,M,geology,experienced,12.0,4,8,...,sikar,"gis expert, data analysis, remote sensing, and...",3,LinkedIn,NaN,1,Not specified,27.583333,75.166667,"27.583333, 75.166667"
443,443,2023-05-28 20:10:37,Sreekanth PA,pursuing graduation/ post graduation in geolog...,B,geoinformatics,fresher,NaN,0,4.5,...,tirunelveli,1. arcgis 2. qgis 3. python,4,LinkedIn,NaN,2,Not specified,8.808234,77.811484,"8.8082342, 77.8114843"
444,444,2023-08-15 23:51:05,SANTOSH,mca,M,other,experienced,60.0,6,9,...,mohali,"arc software, qgis",4,LinkedIn,NaN,1,Not specified,30.704117,76.717688,"30.7041168, 76.7176885"

In [59]:
df_new.to_csv('df3.csv')
df_new.to_excel('df3.xlsx')